name: Generate CSS

on: push

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: ./gradlew run

    - name: Push emoji stylesheet artifact
      uses: actions/upload-artifact@v3
      with:
        path: twemoji-amazing.css

  push_release:
    needs: build_css
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
