name: Generate CSS

on: push

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: ./gradlew run

    - name: Push emoji stylesheet artifact
      uses: actions/upload-artifact@v3
      with:
        path: twemoji-amazing.css

   - name: Push emoji stylesheet to repository
      if: |
        github.event_name == 'workflow_dispatch' &&
        github.repository == 'SebastianAigner/twemoji-amazing'
      run: |
        time=`date '+%Y-%m-%d %H:%M:%S %A (%Z %z)'`
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name  "github-actions[bot]"
        git add twemoji-amazing.css
        git commit -m "Update twemoji - $time" || true
        git push origin || true
